# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.hostname = "http-filestore"
    config.vm.synced_folder "./../..", "/vagrant", type: "nfs"

    config.vm.provider :libvirt do |v|
        v.default_prefix = "http-filestore"
    end
  
    config.vm.provision :shell, path: "./../provision.sh"
    config.vm.network "forwarded_port", guest: 4060, host: 4060
    config.vm.network "forwarded_port", guest: 4061, host: 4061

  end
  